import type { Metadata } from "next";
import "./globals.css";
import { ThemeProviders } from "./theme-providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="text-gray-800 antialiased dark:bg-gray-900 dark:text-gray-400"
      >
        <ThemeProviders>{children}</ThemeProviders>
      </body>
    </html>
  );
}
